### ISSUE TITLE
epic:Display User's Name in Example Component

### ISSUE THREAD

**Issue by ruchitha007** [suhasss077/Project4#1]
As a  Developer,I want to update the Example component to display the user's name, which will be provided dynamically. This enhancement will personalize the component and provide a better user experience.

**Comment by Sharu201101** [comment]
Story Title: Display User's Name in Example Component
As a developer,I want to update the Example component to display the user's name, which will be provided dynamically. This enhancement will personalize the component and provide a better user experience.
Epic Tasks:
Task 1 : date Model Data for Example Component
Description: As a user of the Example component, the model data to be updated to use a name instead of "Unknown name" so that the name is correctly displayed.
Task 2 : Display User's Name and Initial Motto
Description: As a user of the Example component, I want the name and the initial motto from the model data to be displayed so that I can see my name and motto on the page.
Task 3: Apply Styling to Displayed Name and Motto
Description: As a user of the Example component, I want appropriate styling to be applied to the displayed name and motto so that they are visually appealing.
Task 4: Allow User to Update Motto
Description: As a user of the Example component, I want the component to allow me to update the displayed motto through a form input so that I can personalize the motto.

Epic Goals:
Improve Model Data Presentation
Task 1: Update model data to replace "Unknown name" with any name, ensuring accurate display.
Personalize User Information
Task 2: Display the name and initial motto from the model data on the page for a more personalized user experience.
Enhance Visual Appeal
Task 3: Apply appropriate styling to the displayed name and motto to enhance their visual appeal and overall aesthetics.
Enable Motto Personalization
Task 4: Implement functionality allowing users to update their displayed motto through a form input, providing a means for users to personalize their experience further.
By achieving these epic goals, we aim to significantly enhance the user experience within the Example component, making it more engaging, visually pleasing, and personalized to individual users.
